target-version = "py313"
line-length = 88
indent-width = 4

[lint]
select = [
    "E",
    "W",
    "F",
    "B",
    "UP",
    "I",
    "SIM",
    "RUF",
    "C90",
    "DTZ",
    "T20",
    "LOG",
    "G",
    "PTH",
    "C4",
    "S",
    "PERF",
    "RET",
    "ARG",
    "ERA",
]
ignore = [
    "E501",
    "S101",
    "SIM108",
]
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"tests/**/*" = ["S101", "ARG001", "ARG002"]

[lint.isort]
combine-as-imports = true
split-on-trailing-comma = true
lines-after-imports = 2

[lint.mccabe]
max-complexity = 10